version: '2'
services:
    gdsadmin-app:
        image: gdsadmin
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gdsadmin-mysql:3306/gdsadmin?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://gdsadmin-elasticsearch:9200
        ports:
            - 8090:8090
    gdsadmin-mysql:
        extends:
            file: mysql.yml
            service: gdsadmin-mysql
    gdsadmin-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gdsadmin-elasticsearch
